#as we're now activating profiles using spring cloud
#comment below code which is activating this profile using spring boot
#below properties we don't have to send to spring cloud
#our main motto is to send only externalizable props, so common props like server port and h2 db not required
#server:
#  port: 8080
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#  jpa:
#    datasource-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  config:
#    import:
#      - "accounts-qa.yml"
#      - "accounts-prod.yml"
#  profiles:
#    active:
#      - "qa"

build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
