server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3309/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
     init:
        #      saying that always try to execute code that is present inside schema.sql
        #      when using h2 db by default spring boot will execute schema.sql for every start of the app
        #      but when not using this we've to explicitly tell it to execute
        #      when runs for the first time, it will create tables inside cloud docker server
        #      when ran again instead of creating again,. it will use the same table
        #      as we've mentioned create if not present inside schema.sql
        #      when using h2 the db will destroyed when app is stopped, so by default always creates new tables
        #      when using docker db this won't happen
        mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active:
        - "prod"
  application:
    name: "loans"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"




management:
  endpoints:
    web:
      exposure:
        include: "*"
#build:
#  version: "3.0"
#
#loans:
#  message: "Welcome to EazyBank loans related local APIs "
#  contactDetails:
#    name: "Amaal Grega - Developer"
#    email: "amaal@eazybank.com"
#  onCallSupport:
#      - (452) 456-2176
#      - (546) 764-8934